version: '3.5'
services:
  engine:
    container_name: engine
    hostname: engine
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: engine
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/video0:/dev/video0
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
